# IN CLASS LAB EXERCISE - 02

(Kaggle Automobile Dataset)

 We will be using the [automobiles Dataset](https://www.kaggle.com/nisargpatel/automobiles/data) from Kaggle. 

**INCLASS LAB EXERCISE** answer below question. Load pandas as pd and upload the Automobile.csv file as auto


1. symboling: -3, -2, -1, 0, 1, 2, 3. 
2. normalized-losses: continuous from 65 to 256. 
3. make: 
alfa-romero, audi, bmw, chevrolet, dodge, honda, 
isuzu, jaguar, mazda, mercedes-benz, mercury, 
mitsubishi, nissan, peugot, plymouth, porsche, 
renault, saab, subaru, toyota, volkswagen, volvo 

4. fuel-type: diesel, gas. 
5. aspiration: std, turbo. 
6. num-of-doors: four, two. 
7. body-style: hardtop, wagon, sedan, hatchback, convertible. 
8. drive-wheels: 4wd, fwd, rwd. 
9. engine-location: front, rear. 
10. wheel-base: continuous from 86.6 120.9. 
11. length: continuous from 141.1 to 208.1. 
12. width: continuous from 60.3 to 72.3. 
13. height: continuous from 47.8 to 59.8. 
14. curb-weight: continuous from 1488 to 4066. 
15. engine-type: dohc, dohcv, l, ohc, ohcf, ohcv, rotor. 
16. num-of-cylinders: eight, five, four, six, three, twelve, two. 
17. engine-size: continuous from 61 to 326. 
18. fuel-system: 1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi. 
19. bore: continuous from 2.54 to 3.94. 
20. stroke: continuous from 2.07 to 4.17. 
21. compression-ratio: continuous from 7 to 23. 
22. horsepower: continuous from 48 to 288. 
23. peak-rpm: continuous from 4150 to 6600. 
24. city-mpg: continuous from 13 to 49. 
25. highway-mpg: continuous from 16 to 54. 
26. price: continuous from 5118 to 45400.

--------

In [1]:
import pandas as pd

**Q.no(1). Check the head of the DataFrame.**

In [5]:
auto=pd.read_csv("C:\\Users\Asus\\.ipynb_checkpoints\\Automobile.csv")
auto.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

------------------

**Q.no(2). How many rows and columns are there.**

In [6]:
auto.shape

(201, 26)

---------------------

**Q.no(3). What is the average Price of all cars in the dataset.**

In [7]:
auto["price"].mean()

13207.129353233831

-------------------------------

**Q.no(4). Which is the cheapest make and costliest make of car in the lot.**

In [24]:
print("for min : ",auto[auto["price"]==auto["price"].min()]["make"])
print("for max : ",auto[auto["price"]==auto["price"].max()]["make"])

for min :  134    subaru
Name: make, dtype: object
for max :  71    mercedes-benz
Name: make, dtype: object

--------------------

**Q.no(5). How many cars have horsepower greater than 100.**

In [45]:
x=auto[auto["horsepower"]>100]
x["horsepower"].count()

90

----------------

**Q.no(6). How many hatchback cars are in the dataset .**

In [49]:
y=auto[auto["body_style"]=="hatchback"]
y["body_style"].count()

68

-------------------

**Q.no(7). What are the 3 most commonly found cars in the dataset?**

In [ ]:
#doubt

-----

**Q.no(8). Someone purchased a car for 7099, what is the make of the car?**

In [50]:
auto[auto["price"]==7099]["make"]

87    nissan
Name: make, dtype: object

-------------

**Q.no(9). Which cars are priced greater than 40000.**

In [52]:
auto[auto["price"]>40000]["make"]

15              bmw
70    mercedes-benz
71    mercedes-benz
Name: make, dtype: object

---

**Q.no(10). Which are the cars that are both a sedan and priced less than 7000?**

In [78]:
auto[(auto["body_style"]=="sedan") & (auto["price"]>7000)]

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,161,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
10,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
11,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
12,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
13,1,149,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
14,0,149,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
15,0,149,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
16,0,149,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,7609
26,1,148,dodge,gas,turbo,two,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.6,102,5500,24,30,8558
34,0,110,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.2,76,6000,30,34,7295
38,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.0,86,5800,27,33,8845
39,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.0,86,5800,27,33,10295
40,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.0,101,5800,24,28,12945
41,1,107,honda,gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.1,100,5500,25,31,10345
44,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
45,0,115,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,35550
46,0,115,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262,5000,13,17,36000
51,1,113,mazda,gas,std,four,sedan,fwd,front,93.1,...,91,2bbl,3.08,3.15,9.0,68,5000,31,38,7395
57,0,115,mazda,gas,std,four,sedan,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,8495
59,0,115,mazda,gas,std,four,sedan,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10245
60,0,119,mazda,diesel,std,four,sedan,fwd,front,98.8,...,122,idi,3.39,3.39,22.7,64,4650,36,42,10795
62,0,118,mazda,gas,std,four,sedan,rwd,front,104.9,...,140,mpfi,3.76,3.16,8.0,120,5000,19,27,18280
63,0,105,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72,4200,31,39,18344
64,-1,93,mercedes-benz,diesel,turbo,four,sedan,rwd,front,110.0,...,183,idi,3.58,3.64,21.5,123,4350,22,25,25552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,0,102,subaru,gas,std,four,sedan,fwd,front,97.2,...,108,2bbl,3.62,2.64,9.5,82,4400,28,33,7775
139,0,102,subaru,gas,std,four,sedan,fwd,front,97.2,...,108,mpfi,3.62,2.64,9.0,94,5200,26,32,9960
140,0,102,subaru,gas,std,four,sedan,4wd,front,97.0,...,108,2bbl,3.62,2.64,9.0,82,4800,24,25,9233
141,0,102,subaru,gas,turbo,four,sedan,4wd,front,97.0,...,108,mpfi,3.62,2.64,7.7,111,4800,24,29,11259
154,0,91,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56,4500,34,36,7898
156,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70,4800,38,47,7738
158,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70,4800,28,34,9258
159,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70,4800,29,34,8058
161,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112,6600,26,29,9298
169,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,29,34,8948
170,-1,65,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.5,73,4500,30,33,10698
172,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,10898
176,-1,90,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.2,156,5200,20,24,15690
178,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7775
179,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,7975
180,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7995
181,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,8195
182,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,8495
183,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68,4500,37,42,9495
184,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.0,100,5500,26,32,9995
187,0,132,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.5,110,5500,19,24,13295
188,0,132,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
190,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
192,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
194,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

---------------

**Q.no(11) Show the prices of cars in ascending order.**

In [81]:
auto["price"].sort_values()

134     5118
17      5151
47      5195
146     5348
73      5389
31      5399
86      5499
115     5572
20      5572
48      6095
74      6189
23      6229
117     6229
18      6295
147     6338
21      6377
29      6479
148     6488
32      6529
19      6575
88      6649
75      6669
118     6692
24      6692
50      6695
42      6785
49      6795
89      6849
30      6855
149     6918
       ...
133    18620
7      18920
195    18950
197    19045
102    19699
11     20970
12     21105
198    21485
122    22018
199    22470
200    22625
8      23875
13     24565
64     25552
66     28176
65     28248
14     30760
67     31600
44     32250
123    32528
124    34028
68     34184
69     35056
45     35550
46     36000
16     36880
125    37028
70     40960
15     41315
71     45400
Name: price, Length: 201, dtype: int64

--------

**Q.no(12).Show the prices of the cars in descending order.**

In [85]:
auto["price"].sort_values(ascending=False)

71     45400
15     41315
70     40960
125    37028
16     36880
46     36000
45     35550
69     35056
68     34184
124    34028
123    32528
44     32250
67     31600
14     30760
65     28248
66     28176
64     25552
13     24565
8      23875
200    22625
199    22470
122    22018
198    21485
12     21105
11     20970
102    19699
197    19045
195    18950
7      18920
133    18620
       ...
149     6918
30      6855
89      6849
49      6795
42      6785
50      6695
24      6692
118     6692
75      6669
88      6649
19      6575
32      6529
148     6488
29      6479
21      6377
147     6338
18      6295
117     6229
23      6229
74      6189
48      6095
20      5572
115     5572
86      5499
31      5399
73      5389
146     5348
47      5195
17      5151
134     5118
Name: price, Length: 201, dtype: int64

----------------

**Q.no(12).What is the rank order of the cars as per there horsepower.**

In [105]:
auto["Rank"]=auto["horsepower"].rank(ascending=0)
auto.loc[:,["horsepower","Rank"]]

     horsepower   Rank
0           111   68.5
1           111   68.5
2           154   27.0
3           102   82.0
4           115   58.0
5           110   74.5
6           110   74.5
7           110   74.5
8           140   38.0
9           101   87.5
10          101   87.5
11          121   46.0
12          121   46.0
13          121   46.0
14          182    9.0
15          182    9.0
16          182    9.0
17           48  201.0
18           70  153.0
19           70  153.0
20           68  177.0
21           68  177.0
22          102   82.0
23           68  177.0
24           68  177.0
25           68  177.0
26          102   82.0
27           88  118.5
28          145   33.0
29           58  195.0
..          ...    ...
171          92  108.5
172          92  108.5
173          92  108.5
174         161   16.5
175         161   16.5
176         156   23.5
177         156   23.5
178          52  199.5
179          85  127.0
180          52  199.5
181          85  127.0
182          85  127.0
183          68  177.0
184         100   91.5
185          90  113.0
186          90  113.0
187         110   74.5
188          68  177.0
189          88  118.5
190         114   61.5
191         114   61.5
192         114   61.5
193         114   61.5
194         162   14.5
195         162   14.5
196         114   61.5
197         160   20.0
198         134   40.0
199         106   79.0
200         114   61.5

[201 rows x 2 columns]

**Q.no(13).What is the rank order of the cars as per there minimum prices.**

In [106]:
auto["Rank1"]=auto["price"].rank(ascending=1)
auto.loc[:,["price","Rank1"]]

     price  Rank1
0    13495  130.0
1    16500  150.5
2    16500  150.5
3    13950  136.0
4    17450  162.0
5    15250  141.0
6    17710  164.0
7    18920  173.0
8    23875  183.0
9    16430  149.0
10   16925  159.0
11   20970  177.0
12   21105  178.0
13   24565  184.0
14   30760  188.0
15   41315  200.0
16   36880  197.0
17    5151    2.0
18    6295   14.0
19    6575   20.0
20    5572    8.5
21    6377   16.0
22    7957   57.5
23    6229   12.5
24    6692   23.5
25    7609   46.5
26    8558   73.0
27    8921   77.5
28   12964  126.0
29    6479   17.0
..     ...    ...
171   9988   96.0
172  10898  106.0
173  11248  111.0
174  16558  154.0
175  15998  148.0
176  15690  145.0
177  15750  146.0
178   7775   50.5
179   7975   59.0
180   7995   60.0
181   8195   65.0
182   8495   70.5
183   9495   88.0
184   9995   98.0
185  11595  114.0
186   9980   95.0
187  13295  128.0
188  13845  134.0
189  12290  120.0
190  12940  124.0
191  13415  129.0
192  15985  147.0
193  16515  153.0
194  18420  171.0
195  18950  174.0
196  16845  157.0
197  19045  175.0
198  21485  179.0
199  22470  181.0
200  22625  182.0

[201 rows x 2 columns]

------

**Q.no(14).What is the rank order of the cars as per there maximum prices.**

In [107]:
auto["Rank2"]=auto["price"].rank(ascending=0)
auto.loc[:,["price","Rank2"]]

     price  Rank2
0    13495   72.0
1    16500   51.5
2    16500   51.5
3    13950   66.0
4    17450   40.0
5    15250   61.0
6    17710   38.0
7    18920   29.0
8    23875   19.0
9    16430   53.0
10   16925   43.0
11   20970   25.0
12   21105   24.0
13   24565   18.0
14   30760   14.0
15   41315    2.0
16   36880    5.0
17    5151  200.0
18    6295  188.0
19    6575  182.0
20    5572  193.5
21    6377  186.0
22    7957  144.5
23    6229  189.5
24    6692  178.5
25    7609  155.5
26    8558  129.0
27    8921  124.5
28   12964   76.0
29    6479  185.0
..     ...    ...
171   9988  106.0
172  10898   96.0
173  11248   91.0
174  16558   48.0
175  15998   54.0
176  15690   57.0
177  15750   56.0
178   7775  151.5
179   7975  143.0
180   7995  142.0
181   8195  137.0
182   8495  131.5
183   9495  114.0
184   9995  104.0
185  11595   88.0
186   9980  107.0
187  13295   74.0
188  13845   68.0
189  12290   82.0
190  12940   78.0
191  13415   73.0
192  15985   55.0
193  16515   49.0
194  18420   31.0
195  18950   28.0
196  16845   45.0
197  19045   27.0
198  21485   23.0
199  22470   21.0
200  22625   20.0

[201 rows x 2 columns]

**Q.no(15).What is the dense rank order of the cars as per there horsepower.**

In [108]:
auto["Rank3"]=auto["horsepower"].rank(ascending=0,method="dense")
auto.loc[:,["horsepower","Rank3"]]

     horsepower  Rank3
0           111   28.0
1           111   28.0
2           154   13.0
3           102   31.0
4           115   25.0
5           110   29.0
6           110   29.0
7           110   29.0
8           140   18.0
9           101   32.0
10          101   32.0
11          121   22.0
12          121   22.0
13          121   22.0
14          182    5.0
15          182    5.0
16          182    5.0
17           48   58.0
18           70   48.0
19           70   48.0
20           68   50.0
21           68   50.0
22          102   31.0
23           68   50.0
24           68   50.0
25           68   50.0
26          102   31.0
27           88   39.0
28          145   15.0
29           58   54.0
..          ...    ...
171          92   37.0
172          92   37.0
173          92   37.0
174         161    9.0
175         161    9.0
176         156   11.0
177         156   11.0
178          52   57.0
179          85   41.0
180          52   57.0
181          85   41.0
182          85   41.0
183          68   50.0
184         100   33.0
185          90   38.0
186          90   38.0
187         110   29.0
188          68   50.0
189          88   39.0
190         114   26.0
191         114   26.0
192         114   26.0
193         114   26.0
194         162    8.0
195         162    8.0
196         114   26.0
197         160   10.0
198         134   20.0
199         106   30.0
200         114   26.0

[201 rows x 2 columns]

--------------

**Q.no(16). Write a code to display the  `make` and `price` of `5,6,10` rows.**

In [112]:
auto.loc[[5,6,10],["make","price"]]

    make  price
5   audi  15250
6   audi  17710
10   bmw  16925

------

**Q.no(17). Write a code to display the  `first five columns` and  `5 to 10 rows` using as per `index position`.**

In [115]:
auto.iloc[5:11,0:5]

    symboling  normalized_losses  make fuel_type aspiration
5           2                161  audi       gas        std
6           1                158  audi       gas        std
7           1                168  audi       gas        std
8           1                158  audi       gas      turbo
9           2                192   bmw       gas        std
10          0                192   bmw       gas        std

------------------------------------

# ----------------------------------HAPPY LEARNING----------------------------------------

-------